# config.yaml
data_paths:
  tte_nai1: "data/glg_tte_n7_bn090926181_v00.fit"
  tte_nai2: "data/glg_tte_n3_bn090926181_v00.fit"
  tte_bgo1: "data/glg_tte_na_bn201216963_v00.fit"
  cspec_nai1: "data/glg_cspec_n7_bn090926181_v00.pha"
  cspec_nai2: "data/glg_cspec_n3_bn090926181_v00.pha"
  cspec_bgo1: "data/glg_cspec_b0_bn090926181_v00.pha"
  rsp_nai1: "data/glg_cspec_n7_bn090926181_v00.rsp2"
  rsp_nai2: "data/glg_cspec_n3_bn090926181_v00.rsp2"
  rsp_bgo1: "data/glg_cspec_b0_bn090926181_v00.rsp2"

energy_ranges:
  nai: [8.0, 900.0]
  bgo: [325.0, 25000.0]

background:
  pre_bkg_range: [50, 10]
  post_bkg_range: [10, 50]
  polynomial_order: 1

burst_detection:
  percentile_for_bkg: 10
  sigma_threshold: 3

spectral_fitting:
  #model_expression: "Band()"
  #min_values: [1e-10, 0.01, -1.9, -10.0, 0.01]
  #max_values: ["inf", 5e4, 1.5, -2.05, "inf"]
  #default_values: [0.01, 500.0, -0.5, -2.3, 100.0]
  #fixed: [false, false, false, true, false]
  #eval_indices: [1, 2]

  model_expression: "BlackBody() + PowerLaw() + Comptonized()"
  fixed: [true, true, false, true, true, false, true, true, true]
  eval_indices: [1, 6]

  fit_options:
    method: "TNC"
    maxiter: 500
  time_interval: 1.0
  #analysis_start: 5.0   # Iniciar análisis en 5.0 segundos
  #analysis_stop: 15.0  # Detener análisis en 15.0 segundos
  max_fit_time: 10
  relative_error_threshold: 0.2

plotting:
  parameters: ["Epeak", "alpha", "beta", "A"]  # Parámetros a graficar
  save_plots: true
  plots_dir: "results/plots"

output:
  file_name: "results/valid_fits.csv"